path:
  # Specify location of the asset within metaurban, download "asset-model.zip" from github release and put it at corresponding location.
  metaurbanasset: metaurban/../../../assets/objects
  # The parent path for the subfolders below
  parentfolder: metaurban/../../../assets
  subfolders:
    # Major folder, contain annotations for each assets, download "adj_parameter_folder.zip" from github release and put it at corresponding location
    adj_parameter_folder: adj_parameter_folder
